export {
  COLORS,
  DEFAULT_CONFIG,
  HEX_COLOR_PATTERN,
  MOTION_IDS,
  MOTION_LEVELS,
  SURFACE_IDS,
  SURFACES,
  getEyeColor,
  normalizeHexColor,
  normalizeSurface,
  type MotionLevel,
  type MoteConfig,
  type SurfaceConfig,
  type SurfaceId,
  type SurfaceOverrides,
} from './presets.js'
export {
  EYES,
  EYE_IDS,
  eyeById,
  type EyeDefinition,
  type EyeId,
} from './eyes.js'
export {
  SHAPES,
  SHAPE_IDS,
  closedCurvePath,
  shapeById,
  type Point,
  type ShapeDefinition,
  type ShapeId,
} from './shapes.js'
export {
  AVATAR_STATE_IDS,
  AVATAR_STATES,
  DEFAULT_FACE_RIG,
  avatarStateById,
  normalizeFaceRig,
  performanceRigFrames,
  projectEye,
  type AvatarStateDefinition,
  type AvatarStateId,
  type EyeProjection,
  type FaceRigConfig,
  type FaceRigOverrides,
  type FaceRigPerformance,
} from './face-rig.js'
export { generateMoteConfig, type MoteOverrides } from './generate.js'
export { createAvatarSvg, type AvatarSvgOptions } from './svg.js'
export {
  DEFAULT_ANIMATIONS,
  DEFAULT_EXPRESSIONS,
  DEFAULT_EYE_PAIR,
  DEFAULT_EYE_TRANSFORM,
  PLAYBACK_MODES,
  STUDIO_DOCUMENT_VERSION,
  TRANSITION_STYLES,
  activeAvatar,
  behaviorForAvatar,
  createAvatar,
  createDefaultBehavior,
  createStudioDocument,
  detachAvatarBehavior,
  duplicateAvatar,
  normalizeExpression,
  parseStudioDocument,
  serializeStudioDocument,
  type EyePairTransform,
  type EyeTransform,
  type MoteAnimation,
  type MoteAnimationStep,
  type MoteAvatarDocument,
  type MoteBehaviorLibrary,
  type MoteExpression,
  type MoteStudioDocument,
  type PlaybackMode,
  type TransitionStyle,
} from './studio.js'
